### ISSUE TITLE
Unable to run Image classification experiment

### ISSUE THREAD

**Issue by singhsukhendra** [eleGAN23/Hyper#2]
Sir, I am willing to run your experimentation on image classification but failed , can you help how to compare performance of HyperComplex  Neuralnetwork with Hamiltonian product and Qronecker Product on a image dataset.

![Capture](https://user-images.githubusercontent.com/13073082/147768171-565bdae4-fbf5-4923-bc8e-1c95ef99c1b3.JPG)

**Comment by eleGAN23** [comment]
Thanks for opening this issue!
I solved the bug in the name of the model, now it should work.

Happy new year! 😄
